version: '3.8'
services:
    main:
        container_name: 'main'
        build:
          context: .
          target: builder
        networks:
          - webnet
        ports:
          - ${PORT}:${PORT}
          - 9229:9229
        volumes:
          - .:/apps/service-kiosk
          - /apps/service-kiosk/node_modules
        command: yarn start:debug
        env_file:
          - .env
        depends_on:
          - db
    db:
      container_name: 'db'
      image: postgres:12
      networks:
        - webnet
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_DB: ${DB_DATABASE_NAME}
        PG_DATA: /var/lib/postgresql/data
      ports:
        - 5432:5432
      volumes:
        - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata: